conditinal logic

In [1]:
import numpy as np

spending = np.array([500, 2000, 7000, 12000])

# Apply business rule
discount = np.where(
    spending < 1000, 0,
    np.where(spending < 5000, 5, 10)
)

print(discount)

[ 0  5 10 10]


Multi-Condition Filtering

In [2]:
customers = np.array([100, 2000, 6000, 15000])

# High-value customers (5000–15000)
high_value = customers[(customers >= 5000) & (customers <= 15000)]

print(high_value)

[ 6000 15000]


Data Cleaning (Handling Missing Values)

In [3]:
data = np.array([10, 20, np.nan, 40, np.nan])

# Replace NaN with mean
mean = np.nanmean(data)
cleaned = np.where(np.isnan(data), mean, data)

print(cleaned)

[10.         20.         23.33333333 40.         23.33333333]


Aggregations

In [4]:
sales = np.array([100, 200, 300, 400, 500])

print("Total:", np.sum(sales))
print("Average:", np.mean(sales))
print("Max:", np.max(sales))
print("Growth %:", (sales[-1] - sales[0]) / sales[0] * 100)

Total: 1500
Average: 300.0
Max: 500
Growth %: 400.0


Group-like Operations

In [5]:
region = np.array(['A', 'B', 'A', 'B'])
revenue = np.array([100, 200, 300, 400])

# Sum revenue for region A
print(np.sum(revenue[region == 'A']))

400


Broadcasting (scaling Data)

In [6]:
prices = np.array([100, 200, 300])
tax_rate = 0.13

final_price = prices + prices * tax_rate
print(final_price)

[113. 226. 339.]


Matrix Operations

In [7]:
# Product sales matrix
sales = np.array([[10, 20],
                  [30, 40]])

# Multiply with price vector
price = np.array([5, 10])

revenue = sales @ price
print(revenue)

[250 550]


Outliers

In [8]:
data = np.array([10, 12, 11, 500, 13, 12])

mean = np.mean(data)
std = np.std(data)

outliers = data[np.abs(data - mean) > 2 * std]
print(outliers)

[500]
