In [1]:
import numpy as np

In [2]:
print (np.__version__)

2.4.1


#creating arrays
1D array

In [3]:
list1 = [1,2,3,4,5]
print (list1)

[1, 2, 3, 4, 5]


In [4]:
arr_list1 = np.array(list1)
print (arr_list1)

[1 2 3 4 5]


In [5]:
print(type(list1))
print(type(arr_list1))

<class 'list'>
<class 'numpy.ndarray'>


2D array

In [6]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
array_list = np.array([list1, list2])
print(array_list)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


3D array

In [7]:
import numpy as np
arr1 = [1,2,3,4,5]
arr2 = [6,7,8,9,10]
arr3 = [11,12,13,14,15]
array_list = np.array([arr1, arr2, arr3])
print(array_list)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


python vs numpy array

In [43]:
py_list = [1,2,3,4]
print("Python list multiplication:", py_list * 2)

Python list multiplication: [1, 2, 3, 4, 1, 2, 3, 4]


In [44]:
import numpy as np
np_array = np.array([1,2,3,4]) #Element wise multiplication 
print("Numpy multiplication:", np_array * 2)

Numpy multiplication: [2 4 6 8]


Numpy array attributes

In [45]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr1)


[[1 2 3]
 [4 5 6]]


In [46]:
print("Shape", arr1.shape)
print("Size", arr1.size)
print("Data type", arr1.dtype)
print("n_dim", arr1.ndim)

Shape (2, 3)
Size 6
Data type int64
n_dim 2


Array intialization Methos
Zeros array
ones array
full array

In [47]:
#zeros array
zero_arr = np.zeros((3,4))
print(zero_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [48]:
#ones array
ones_arr = np.ones((2,3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [49]:
#full array
full_arr = np.full((2,3), 7)
print(full_arr)

[[7 7 7]
 [7 7 7]]


In [50]:
#identity matrix
identity_arr = np.eye(4)
print(identity_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [51]:
#empty array
empty_arr = np.empty((2))
print(empty_arr)

[5.43230922e-312 7.29112202e-304]


Array indexing & Slicing

In [52]:
a = np.array([1, 2, 3, 4, 5])
print(a[4])

5


#silicing [start: stop:step]

In [53]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a[0:3]) #first 3 elements

[1 2 3]


In [54]:
print(a[-3:]) #last 3 elements

[3 4 5]


In [55]:
print(a[0::3]) #Middle 3 elements with steps

[1 4]


In [56]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [57]:
print(arr2[0])

[1 2 3]


In [58]:
print(arr2[0][1])

2


In [59]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [60]:
arr1 = np.array([1, 2, 3, 4, 5])
reshaped = arr1.reshape((5, 1))
print(reshaped)


[[1]
 [2]
 [3]
 [4]
 [5]]


In [61]:
reshaped2 = arr1.reshape((5, 1))
print(reshaped2)


[[1]
 [2]
 [3]
 [4]
 [5]]


In [62]:
print(reshaped2.flatten())

[1 2 3 4 5]


iterate on 1D array

In [63]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


Iterate on 2D array

In [64]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


Filtering

In [ ]:
a = np.array([10,20,30,40])
filtered = a[a > 20]
print(filtered)

[30 40]


Filter with mask

In [233]:
a = np.array([10,20,30,40])
mask = a > 25
print("Number greater than 25 is", a[mask])

Number greater than 25 is [30 40]


array stacking & splitting

In [234]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b))) #Vertical stack
print(np.hstack((a,b))) #Horizontal stack

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [235]:
c = np.array([[1,2],[3,4]])
print(c)

[[1 2]
 [3 4]]


In [236]:
print(np.hsplit(c, 2)) #Horizontal split

[array([[1],
       [3]]), array([[2],
       [4]])]


In [237]:
split = np.hsplit(c, 2)
for s in split:
    print(s)

[[1]
 [3]]
[[2]
 [4]]


In [238]:
vsplit = np.vsplit(c, 2)
for s in vsplit:
    print(s)

[[1 2]]
[[3 4]]


In [239]:
#Mathematical operations on array
a = np.array([10,20,30])
print(a)

[10 20 30]


In [240]:
print(a+10)
print(a-10)
print(a*10)
print(a/10)

[20 30 40]
[ 0 10 20]
[100 200 300]
[1. 2. 3.]


In [241]:
b = np.array([1,2,3])
print(b)

[1 2 3]


In [242]:
print(np.square(b))
print(np.sqrt(b))

[1 4 9]
[1.         1.41421356 1.73205081]


In [243]:
#Mathematical operations on multiple arrays
a  = np.array([1,2,3])
b = np.array([4, 5, 6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [244]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [245]:
print(np.dot(a,b))

32


In [246]:
print(a.T)

[1 2 3]


In [247]:
t = np.array([[1,2,3], 
              [4,5,6]])
print(t)
print(t.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [248]:
#statistical operations
a = np.array([[1,2,3], [4,5,6]])
print(np.sum(a))

21


In [249]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6


In [250]:
a = np.array([1,5,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 5 3]
[4 5 6]


In [251]:
print(a == b)
print(np.array_equal(a,b))

[False  True False]
False


save and load arrays

In [252]:
arr = np.array([1,0,0,8])
print(arr)
np.save('my_array.npy', arr)


[1 0 0 8]


In [253]:
loaded_arr = np.load('my_array.npy')
print(loaded_arr)

[1 0 0 8]
